// 门店决策卡
const STORE_DATA = [
  {p:"BBQ",n:"中式烧烤",e:"🔥",c:[{f:"catalog/BBQ/BBQ_M01_中式烧烤创业母卡.html",n:"BBQ_M01_中式烧烤创业母卡"},{f:"catalog/BBQ/BBQ_T01_中式烧烤总纲.html",n:"BBQ_T01_中式烧烤总纲"},{f:"catalog/BBQ/BBQ_V01_腌料体系.html",n:"BBQ_V01_腌料体系"},{f:"catalog/BBQ/BBQ_V02_酱料体系.html",n:"BBQ_V02_酱料体系"},{f:"catalog/BBQ/BBQ_V03_撒料体系.html",n:"BBQ_V03_撒料体系"},{f:"catalog/BBQ/BBQ_V04_味型体系.html",n:"BBQ_V04_味型体系"},{f:"catalog/BBQ/BBQ_V05_地摊自助烤肉模式.html",n:"BBQ_V05_地摊自助烤肉模式"},{f:"catalog/BBQ/BBQ_V06_纸上烤肉门店模式.html",n:"BBQ_V06_纸上烤肉门店模式"}]},
  {p:"SL",n:"烧腊体系",e:"🍗",c:[{f:"catalog/SL/SL_M01_烧腊创业母卡.html",n:"SL_M01_烧腊创业母卡"},{f:"catalog/SL/SL_T01_烧腊总纲.html",n:"SL_T01_烧腊总纲"},{f:"catalog/SL/SL_V01_腌制与皮水体系.html",n:"SL_V01_腌制与皮水体系"},{f:"catalog/SL/SL_V02_烘烤与火候体系.html",n:"SL_V02_烘烤与火候体系"},{f:"catalog/SL/SL_V03_蘸料与卤水体系.html",n:"SL_V03_蘸料与卤水体系"},{f:"catalog/SL/SL_V04_斩切与出品体系.html",n:"SL_V04_斩切与出品体系"}]},
  {p:"KR",n:"韩式烤肉",e:"🥩",c:[{f:"catalog/KR/KR_001_秘制大块肉.html",n:"KR_001_秘制大块肉"},{f:"catalog/KR/KR_002_厚切五花肉.html",n:"KR_002_厚切五花肉"},{f:"catalog/KR/KR_003_LA牛排.html",n:"KR_003_LA牛排"},{f:"catalog/KR/KR_004_烤护心肉.html",n:"KR_004_烤护心肉"},{f:"catalog/KR/KR_005_烤大肠.html",n:"KR_005_烤大肠"},{f:"catalog/KR/KR_006_烤猪皮.html",n:"KR_006_烤猪皮"},{f:"catalog/KR/KR_01_韩式肥牛系列.html",n:"KR_01_韩式肥牛系列"},{f:"catalog/KR/KR_02_韩式厚切系列.html",n:"KR_02_韩式厚切系列"},{f:"catalog/KR/KR_03_韩式猪羊特色系列.html",n:"KR_03_韩式猪羊特色系列"},{f:"catalog/KR/KR_S_地摊烤肉精简版.html",n:"KR_S_地摊烤肉精简版"}]},
  {p:"KF",n:"韩式汤/主食",e:"🍲",c:[{f:"catalog/KF/KF_001_石锅拌饭.html",n:"KF_001_石锅拌饭"},{f:"catalog/KF/KF_002_冷面.html",n:"KF_002_冷面"},{f:"catalog/KF/KF_003_大酱汤.html",n:"KF_003_大酱汤"},{f:"catalog/KF/KF_004_嫩豆腐汤.html",n:"KF_004_嫩豆腐汤"},{f:"catalog/KF/KF_005_肥牛拌饭.html",n:"KF_005_肥牛拌饭"},{f:"catalog/KF/KF_006_辣白菜炒饭.html",n:"KF_006_辣白菜炒饭"},{f:"catalog/KF/KF_007_海鲜葱饼.html",n:"KF_007_海鲜葱饼"},{f:"catalog/KF/KF_008_辣炒年糕.html",n:"KF_008_辣炒年糕"},{f:"catalog/KF/KF_009_泡菜汤.html",n:"KF_009_泡菜汤"},{f:"catalog/KF/KF_010_部队锅.html",n:"KF_010_部队锅"},{f:"catalog/KF/KF_011_参鸡汤.html",n:"KF_011_参鸡汤"},{f:"catalog/KF/KF_012_排骨汤.html",n:"KF_012_排骨汤"}]},
  {p:"PC",n:"韩式拌菜",e:"🥬",c:[{f:"catalog/PC/PC_K01_韩式辣白菜系列.html",n:"PC_K01_韩式辣白菜系列"},{f:"catalog/PC/PC_K02_韩式牛副拌菜.html",n:"PC_K02_韩式牛副拌菜"},{f:"catalog/PC/PC_K03_韩式明太鱼系列.html",n:"PC_K03_韩式明太鱼系列"},{f:"catalog/PC/PC_K04_韩式豆制品系列.html",n:"PC_K04_韩式豆制品系列"},{f:"catalog/PC/PC_K05_韩式腌菜拌菜系列.html",n:"PC_K05_韩式腌菜拌菜系列"},{f:"catalog/PC/PC_K06_韩式拌豆芽.html",n:"PC_K06_韩式拌豆芽"},{f:"catalog/PC/PC_K07_韩式炒鱼饼.html",n:"PC_K07_韩式炒鱼饼"},{f:"catalog/PC/PC_K08_韩式拌菠菜.html",n:"PC_K08_韩式拌菠菜"}]},
  {p:"JL",n:"韩式酱料",e:"🧂",c:[{f:"catalog/JL/JL_020_韩式烤肉蘸酱.html",n:"JL_020_韩式烤肉蘸酱"},{f:"catalog/JL/JL_021_韩式大酱.html",n:"JL_021_韩式大酱"},{f:"catalog/JL/JL_022_韩式辣椒酱.html",n:"JL_022_韩式辣椒酱"}]},
  {p:"J",n:"鸡系列",e:"🐔",c:[{f:"catalog/J/J01 五香整鸡（母）.html",n:"J01 五香整鸡（母）"},{f:"catalog/J/J02 德州扒鸡（母）.html",n:"J02 德州扒鸡（母）"},{f:"catalog/J/J03 五香烧鸡（母）.html",n:"J03 五香烧鸡（母）"},{f:"catalog/J/J04 风干鸡（母）.html",n:"J04 风干鸡（母）"},{f:"catalog/J/J05 八珍药膳鸡（母）.html",n:"J05 八珍药膳鸡（母）"},{f:"catalog/J/J06 五香鸡爪（母）.html",n:"J06 五香鸡爪（母）"},{f:"catalog/J/J07 五香鸡翅（母）.html",n:"J07 五香鸡翅（母）"},{f:"catalog/J/J08 五香鸡腿（母）.html",n:"J08 五香鸡腿（母）"},{f:"catalog/J/J09 五香鸡胗（母）.html",n:"J09 五香鸡胗（母）"},{f:"catalog/J/J10 五香虎皮风爪（母）.html",n:"J10 五香虎皮风爪（母）"},{f:"catalog/J/J11 五香虎皮鸡腿（母）.html",n:"J11 五香虎皮鸡腿（母）"},{f:"catalog/J/J12 五香虎皮鸡头（母）.html",n:"J12 五香虎皮鸡头（母）"},{f:"catalog/J/J13 五香鸡头（母）.html",n:"J13 五香鸡头（母）"},{f:"catalog/J/J14 五香鸡肝（母）.html",n:"J14 五香鸡肝（母）"},{f:"catalog/J/J15 五香鸡心（母）.html",n:"J15 五香鸡心（母）"},{f:"catalog/J/J16 五香鸡肚（母）.html",n:"J16 五香鸡肚（母）"},{f:"catalog/J/JL_020_韩式烤肉蘸酱.html",n:"JL_020_韩式烤肉蘸酱"},{f:"catalog/J/JL_021_韩式大酱.html",n:"JL_021_韩式大酱"},{f:"catalog/J/JL_022_韩式辣椒酱.html",n:"JL_022_韩式辣椒酱"}]},
  {p:"Z",n:"猪系列",e:"🐷",c:[{f:"catalog/Z/Z01 五香猪头肉（母）.html",n:"Z01 五香猪头肉（母）"},{f:"catalog/Z/Z02 五香猪蹄（母）.html",n:"Z02 五香猪蹄（母）"},{f:"catalog/Z/Z03 五香猪尾巴.html",n:"Z03 五香猪尾巴"},{f:"catalog/Z/Z04 五香猪肘子带骨.html",n:"Z04 五香猪肘子带骨"},{f:"catalog/Z/Z05 五香猪耳朵.html",n:"Z05 五香猪耳朵"},{f:"catalog/Z/Z06 五香猪皮卷.html",n:"Z06 五香猪皮卷"},{f:"catalog/Z/Z07 五香猪口条.html",n:"Z07 五香猪口条"},{f:"catalog/Z/Z08 五香猪肝.html",n:"Z08 五香猪肝"},{f:"catalog/Z/Z09 五香猪心.html",n:"Z09 五香猪心"},{f:"catalog/Z/Z10 五香猪大肠.html",n:"Z10 五香猪大肠"},{f:"catalog/Z/Z11 五香猪连心肉.html",n:"Z11 五香猪连心肉"},{f:"catalog/Z/ZHA_M01_炸串创业母卡.html",n:"ZHA_M01_炸串创业母卡"},{f:"catalog/Z/ZHA_T01_炸串总纲.html",n:"ZHA_T01_炸串总纲"},{f:"catalog/Z/ZHA_V01_炸串挂糊体系.html",n:"ZHA_V01_炸串挂糊体系"},{f:"catalog/Z/ZHA_V02_炸串酱料体系.html",n:"ZHA_V02_炸串酱料体系"},{f:"catalog/Z/ZHA_V03_炸串撒料体系.html",n:"ZHA_V03_炸串撒料体系"}]},
  {p:"B",n:"牛系列",e:"🐮",c:[{f:"catalog/B/B01 五香牛腱.html",n:"B01 五香牛腱"},{f:"catalog/B/B02 酱香牛肉.html",n:"B02 酱香牛肉"},{f:"catalog/B/B03 五香牛头肉.html",n:"B03 五香牛头肉"},{f:"catalog/B/B04 五香牛肝.html",n:"B04 五香牛肝"},{f:"catalog/B/B05 五香牛肚.html",n:"B05 五香牛肚"},{f:"catalog/B/B06 五香黄喉.html",n:"B06 五香黄喉"},{f:"catalog/B/B07 五香牛腩.html",n:"B07 五香牛腩"},{f:"catalog/B/B08 五香牛蹄筋.html",n:"B08 五香牛蹄筋"},{f:"catalog/B/B09 夫妻肺片.html",n:"B09 夫妻肺片"},{f:"catalog/B/BBQ_M01_中式烧烤创业母卡.html",n:"BBQ_M01_中式烧烤创业母卡"},{f:"catalog/B/BBQ_T01_中式烧烤总纲.html",n:"BBQ_T01_中式烧烤总纲"},{f:"catalog/B/BBQ_V01_腌料体系.html",n:"BBQ_V01_腌料体系"},{f:"catalog/B/BBQ_V02_酱料体系.html",n:"BBQ_V02_酱料体系"},{f:"catalog/B/BBQ_V03_撒料体系.html",n:"BBQ_V03_撒料体系"},{f:"catalog/B/BBQ_V04_味型体系.html",n:"BBQ_V04_味型体系"},{f:"catalog/B/BBQ_V05_地摊自助烤肉模式.html",n:"BBQ_V05_地摊自助烤肉模式"},{f:"catalog/B/BBQ_V06_纸上烤肉门店模式.html",n:"BBQ_V06_纸上烤肉门店模式"}]},
  {p:"E",n:"鹅系列",e:"🦆",c:[{f:"catalog/E/E01 五香鹅翅.html",n:"E01 五香鹅翅"},{f:"catalog/E/E02 五香鹅掌.html",n:"E02 五香鹅掌"},{f:"catalog/E/E03 五香鹅头.html",n:"E03 五香鹅头"},{f:"catalog/E/E04 五香鹅肠.html",n:"E04 五香鹅肠"}]},
  {p:"LW",n:"卤味体系",e:"🫘",c:[{f:"catalog/LW/LW001 卤鸭脖（母）LW_001.html",n:"LW001 卤鸭脖（母）LW_001"},{f:"catalog/LW/LW001 卤鸭脖（母）样卡.html",n:"LW001 卤鸭脖（母）样卡"},{f:"catalog/LW/LW002 卤鸭翅（母）LW_002.html",n:"LW002 卤鸭翅（母）LW_002"},{f:"catalog/LW/LW003 卤鸭掌（母）LW_003.html",n:"LW003 卤鸭掌（母）LW_003"},{f:"catalog/LW/LW004 卤鸭头（母）LW_004.html",n:"LW004 卤鸭头（母）LW_004"},{f:"catalog/LW/LW005 卤鸭锁骨（母）LW_005.html",n:"LW005 卤鸭锁骨（母）LW_005"}]},
  {p:"VC",n:"卤味·变体",e:"🌶️",c:[{f:"catalog/VC/VC001 麻辣鸭脖.html",n:"VC001 麻辣鸭脖"},{f:"catalog/VC/VC002 酱香鸭脖.html",n:"VC002 酱香鸭脖"},{f:"catalog/VC/VC003 藤椒鸭脖.html",n:"VC003 藤椒鸭脖"},{f:"catalog/VC/VC004 麻辣鸭翅.html",n:"VC004 麻辣鸭翅"},{f:"catalog/VC/VC005 酱香鸭翅.html",n:"VC005 酱香鸭翅"},{f:"catalog/VC/VC006 藤椒鸭翅.html",n:"VC006 藤椒鸭翅"},{f:"catalog/VC/VC007 麻辣鸭掌.html",n:"VC007 麻辣鸭掌"},{f:"catalog/VC/VC008 酱香鸭掌.html",n:"VC008 酱香鸭掌"},{f:"catalog/VC/VC009 藤椒鸭掌.html",n:"VC009 藤椒鸭掌"},{f:"catalog/VC/VC010 麻辣鸭头.html",n:"VC010 麻辣鸭头"},{f:"catalog/VC/VC011 酱香鸭头.html",n:"VC011 酱香鸭头"},{f:"catalog/VC/VC012 藤椒鸭头.html",n:"VC012 藤椒鸭头"},{f:"catalog/VC/VC013 麻辣锁骨.html",n:"VC013 麻辣锁骨"},{f:"catalog/VC/VC014 酱香锁骨.html",n:"VC014 酱香锁骨"},{f:"catalog/VC/VC015 藤椒锁骨.html",n:"VC015 藤椒锁骨"},{f:"catalog/VC/VC016 麻辣鸭舌.html",n:"VC016 麻辣鸭舌"},{f:"catalog/VC/VC017 酱香鸭舌.html",n:"VC017 酱香鸭舌"},{f:"catalog/VC/VC018 藤椒鸭舌.html",n:"VC018 藤椒鸭舌"},{f:"catalog/VC/VC019 麻辣鸭肠.html",n:"VC019 麻辣鸭肠"},{f:"catalog/VC/VC020 酱香鸭肠.html",n:"VC020 酱香鸭肠"},{f:"catalog/VC/VC021 藤椒鸭肠.html",n:"VC021 藤椒鸭肠"},{f:"catalog/VC/VC022 麻辣板肠.html",n:"VC022 麻辣板肠"},{f:"catalog/VC/VC023 酱香板肠.html",n:"VC023 酱香板肠"},{f:"catalog/VC/VC024 藤椒板肠.html",n:"VC024 藤椒板肠"},{f:"catalog/VC/VC025 麻辣鸭腿.html",n:"VC025 麻辣鸭腿"},{f:"catalog/VC/VC026 酱香鸭腿.html",n:"VC026 酱香鸭腿"},{f:"catalog/VC/VC027 藤椒鸭腿.html",n:"VC027 藤椒鸭腿"},{f:"catalog/VC/VC028 麻辣鸭心.html",n:"VC028 麻辣鸭心"},{f:"catalog/VC/VC029 酱香鸭心.html",n:"VC029 酱香鸭心"},{f:"catalog/VC/VC030 藤椒鸭心.html",n:"VC030 藤椒鸭心"},{f:"catalog/VC/VC031 麻辣鸭胗.html",n:"VC031 麻辣鸭胗"},{f:"catalog/VC/VC032 酱香鸭胗.html",n:"VC032 酱香鸭胗"},{f:"catalog/VC/VC033 藤椒鸭胗.html",n:"VC033 藤椒鸭胗"},{f:"catalog/VC/VC_K001_牛肉调味系列.html",n:"VC_K001_牛肉调味系列"},{f:"catalog/VC/VC_K002_原味牛肉系列.html",n:"VC_K002_原味牛肉系列"},{f:"catalog/VC/VC_K003_猪羊特色系列.html",n:"VC_K003_猪羊特色系列"},{f:"catalog/VC/VC_K004_秘制烤肉系列.html",n:"VC_K004_秘制烤肉系列"},{f:"catalog/VC/VC年糕无骨炸鸡（子）HZ_026.html",n:"VC年糕无骨炸鸡（子）HZ_026"},{f:"catalog/VC/VC蜜汁酱（子）JL_010.html",n:"VC蜜汁酱（子）JL_010"},{f:"catalog/VC/VC蜜汁鸡块（子）HZ_009.html",n:"VC蜜汁鸡块（子）HZ_009"}]},
  {p:"SC",n:"素菜系列",e:"🥗",c:[{f:"catalog/SC/SC01 甜辣藕片（素菜·免费）.html",n:"SC01 甜辣藕片（素菜·免费）"},{f:"catalog/SC/SC02 甜辣土豆片（素菜·免费）.html",n:"SC02 甜辣土豆片（素菜·免费）"},{f:"catalog/SC/SC03 麻辣红油腐竹（素菜·免费）.html",n:"SC03 麻辣红油腐竹（素菜·免费）"},{f:"catalog/SC/SC04 麻辣红油豆干（素菜·免费）.html",n:"SC04 麻辣红油豆干（素菜·免费）"},{f:"catalog/SC/SC05 五香鸡汤千张（素菜·免费）.html",n:"SC05 五香鸡汤千张（素菜·免费）"},{f:"catalog/SC/SC06 五香鸡汤海带丝（素菜·免费）.html",n:"SC06 五香鸡汤海带丝（素菜·免费）"}]},
  {p:"CJ",n:"炒鸡体系",e:"🍳",c:[{f:"catalog/CJ/CJ_M01_炒鸡创业母卡.html",n:"CJ_M01_炒鸡创业母卡"},{f:"catalog/CJ/CJ_T01_炒鸡总纲.html",n:"CJ_T01_炒鸡总纲"},{f:"catalog/CJ/CJ_V01_炒鸡工艺体系.html",n:"CJ_V01_炒鸡工艺体系"},{f:"catalog/CJ/CJ_V02_炒鸡配套体系.html",n:"CJ_V02_炒鸡配套体系"}]},
  {p:"GS",n:"贵州酸汤",e:"🥘",c:[{f:"catalog/GS/GS_M01_贵州酸汤创业母卡.html",n:"GS_M01_贵州酸汤创业母卡"},{f:"catalog/GS/GS_T01_贵州酸汤总纲.html",n:"GS_T01_贵州酸汤总纲"},{f:"catalog/GS/GS_V01_贵州酸汤发酵高汤体系.html",n:"GS_V01_贵州酸汤发酵高汤体系"},{f:"catalog/GS/GS_V02_贵州酸汤蘸水蘸料体系.html",n:"GS_V02_贵州酸汤蘸水蘸料体系"},{f:"catalog/GS/GS_V03_贵州酸汤涮品搭配体系.html",n:"GS_V03_贵州酸汤涮品搭配体系"}]},
  {p:"HG",n:"火锅体系",e:"🫕",c:[{f:"catalog/HG/HG_M01_火锅创业母卡.html",n:"HG_M01_火锅创业母卡"},{f:"catalog/HG/HG_T01_火锅总纲.html",n:"HG_T01_火锅总纲"},{f:"catalog/HG/HG_V01_火锅底料配方体系.html",n:"HG_V01_火锅底料配方体系"},{f:"catalog/HG/HG_V02_火锅蘸料体系.html",n:"HG_V02_火锅蘸料体系"},{f:"catalog/HG/HG_V03_火锅涮品搭配体系.html",n:"HG_V03_火锅涮品搭配体系"}]},
  {p:"HM",n:"河南烩面",e:"🍜",c:[{f:"catalog/HM/HM_M01_河南烩面创业母卡.html",n:"HM_M01_河南烩面创业母卡"},{f:"catalog/HM/HM_T01_河南烩面总纲.html",n:"HM_T01_河南烩面总纲"},{f:"catalog/HM/HM_V01_烩面汤底扯面工艺.html",n:"HM_V01_烩面汤底扯面工艺"},{f:"catalog/HM/HM_V02_烩面浇头配菜体系.html",n:"HM_V02_烩面浇头配菜体系"}]},
  {p:"KY",n:"烤鱼体系",e:"🐟",c:[{f:"catalog/KY/KY_M01_烤鱼创业母卡.html",n:"KY_M01_烤鱼创业母卡"},{f:"catalog/KY/KY_T01_烤鱼总纲.html",n:"KY_T01_烤鱼总纲"},{f:"catalog/KY/KY_V01_烤鱼底料酱料体系.html",n:"KY_V01_烤鱼底料酱料体系"},{f:"catalog/KY/KY_V02_烤鱼腌料撒料体系.html",n:"KY_V02_烤鱼腌料撒料体系"},{f:"catalog/KY/KY_V03_烤鱼浇头配菜体系.html",n:"KY_V03_烤鱼浇头配菜体系"}]},
  {p:"MLT",n:"麻辣烫冒菜",e:"🥘",c:[{f:"catalog/MLT/MLT_M01_麻辣烫冒菜创业母卡.html",n:"MLT_M01_麻辣烫冒菜创业母卡"},{f:"catalog/MLT/MLT_T01_麻辣烫冒菜总纲.html",n:"MLT_T01_麻辣烫冒菜总纲"},{f:"catalog/MLT/MLT_V01_麻辣烫冒菜底料体系.html",n:"MLT_V01_麻辣烫冒菜底料体系"},{f:"catalog/MLT/MLT_V02_麻辣烫冒菜碗底料体系.html",n:"MLT_V02_麻辣烫冒菜碗底料体系"},{f:"catalog/MLT/MLT_V03_麻辣烫冒菜蘸料干碟体系.html",n:"MLT_V03_麻辣烫冒菜蘸料干碟体系"}]},
  {p:"XLX",n:"小龙虾",e:"🦞",c:[{f:"catalog/XLX/XLX_M01_小龙虾创业母卡.html",n:"XLX_M01_小龙虾创业母卡"},{f:"catalog/XLX/XLX_T01_小龙虾总纲.html",n:"XLX_T01_小龙虾总纲"},{f:"catalog/XLX/XLX_V01_小龙虾底料调味体系.html",n:"XLX_V01_小龙虾底料调味体系"},{f:"catalog/XLX/XLX_V02_小龙虾清洗过油炒制工艺.html",n:"XLX_V02_小龙虾清洗过油炒制工艺"},{f:"catalog/XLX/XLX_V03_小龙虾配菜蘸料虾尾衍生品.html",n:"XLX_V03_小龙虾配菜蘸料虾尾衍生品"}]},
  {p:"YN",n:"云南米线",e:"🍜",c:[{f:"catalog/YN/YN_M01_云南米线创业母卡.html",n:"YN_M01_云南米线创业母卡"},{f:"catalog/YN/YN_T01_云南米线总纲.html",n:"YN_T01_云南米线总纲"},{f:"catalog/YN/YN_V01_云南米线汤底帽子体系.html",n:"YN_V01_云南米线汤底帽子体系"},{f:"catalog/YN/YN_V02_云南米线过桥小锅技法.html",n:"YN_V02_云南米线过桥小锅技法"},{f:"catalog/YN/YN_V03_云南米线辅料蘸水配菜体系.html",n:"YN_V03_云南米线辅料蘸水配菜体系"}]},
  {p:"ZHA",n:"中式炸串",e:"🍢",c:[{f:"catalog/ZHA/ZHA_M01_炸串创业母卡.html",n:"ZHA_M01_炸串创业母卡"},{f:"catalog/ZHA/ZHA_T01_炸串总纲.html",n:"ZHA_T01_炸串总纲"},{f:"catalog/ZHA/ZHA_V01_炸串挂糊体系.html",n:"ZHA_V01_炸串挂糊体系"},{f:"catalog/ZHA/ZHA_V02_炸串酱料体系.html",n:"ZHA_V02_炸串酱料体系"},{f:"catalog/ZHA/ZHA_V03_炸串撒料体系.html",n:"ZHA_V03_炸串撒料体系"}]},
];

// 地摊产品卡
const STALL_DATA = [
  {p:"KF",n:"咖啡饮品",e:"☕",c:[{f:"catalog/其他/KF_001_石锅拌饭.html",n:"KF_001_石锅拌饭"},{f:"catalog/其他/KF_002_冷面.html",n:"KF_002_冷面"},{f:"catalog/其他/KF_003_大酱汤.html",n:"KF_003_大酱汤"},{f:"catalog/其他/KF_004_嫩豆腐汤.html",n:"KF_004_嫩豆腐汤"},{f:"catalog/其他/KF_005_肥牛拌饭.html",n:"KF_005_肥牛拌饭"},{f:"catalog/其他/KF_006_辣白菜炒饭.html",n:"KF_006_辣白菜炒饭"},{f:"catalog/其他/KF_007_海鲜葱饼.html",n:"KF_007_海鲜葱饼"},{f:"catalog/其他/KF_008_辣炒年糕.html",n:"KF_008_辣炒年糕"},{f:"catalog/其他/KF_009_泡菜汤.html",n:"KF_009_泡菜汤"},{f:"catalog/其他/KF_010_部队锅.html",n:"KF_010_部队锅"},{f:"catalog/其他/KF_011_参鸡汤.html",n:"KF_011_参鸡汤"},{f:"catalog/其他/KF_012_排骨汤.html",n:"KF_012_排骨汤"}]},
  {p:"PC",n:"拌菜系列",e:"🥗",c:[{f:"catalog/其他/PC_K01_韩式辣白菜系列.html",n:"PC_K01_韩式辣白菜系列"},{f:"catalog/其他/PC_K02_韩式牛副拌菜.html",n:"PC_K02_韩式牛副拌菜"},{f:"catalog/其他/PC_K03_韩式明太鱼系列.html",n:"PC_K03_韩式明太鱼系列"},{f:"catalog/其他/PC_K04_韩式豆制品系列.html",n:"PC_K04_韩式豆制品系列"},{f:"catalog/其他/PC_K05_韩式腌菜拌菜系列.html",n:"PC_K05_韩式腌菜拌菜系列"},{f:"catalog/其他/PC_K06_韩式拌豆芽.html",n:"PC_K06_韩式拌豆芽"},{f:"catalog/其他/PC_K07_韩式炒鱼饼.html",n:"PC_K07_韩式炒鱼饼"},{f:"catalog/其他/PC_K08_韩式拌菠菜.html",n:"PC_K08_韩式拌菠菜"}]},
  {p:"JL",n:"酱料蘸料",e:"🧂",c:[{f:"catalog/其他/JL_020_韩式烤肉蘸酱.html",n:"JL_020_韩式烤肉蘸酱"},{f:"catalog/其他/JL_021_韩式大酱.html",n:"JL_021_韩式大酱"},{f:"catalog/其他/JL_022_韩式辣椒酱.html",n:"JL_022_韩式辣椒酱"}]},
];

function renderCards(id,data,exp){
  var el=document.getElementById(id);
  if(!el)return;
  data.forEach(function(d){
    var h='<div class="cat-card"><div class="cc-header" onclick="this.classList.toggle(\'active\');var b=this.nextElementSibling;b.classList.toggle(\'hide\')"><span>'+d.e+'</span> '+d.n+'<span class="cc-count">'+d.c.length+'张</span><span class="cc-arrow">'+(exp?'&#9660;':'&#9654;')+'</span></div><div class="cc-body'+(exp?'':' hide')+'"><div class="cat-grid">';
    d.c.forEach(function(c){h+='<a href="'+c.f+'"><span>'+d.e+'</span><span class="cg-name">'+c.n+'</span><span class="cg-arrow">&#8250;</span></a>';});
    h+='</div></div></div>';
    el.innerHTML+=h;
  });
}
document.addEventListener('DOMContentLoaded',function(){renderCards('storeCards',STORE_DATA,true);renderCards('stallCards',STALL_DATA,true);});
