// 自动生成 - 所有产品卡数据
const ALL_CARDS = {
  "☕ 咖啡系列": [
    {e:"📄", n:"经典美式咖啡 CF-01 · 沧林食品", d:"", f:"cards/CF-01.html"},
    {e:"📄", n:"生椰拿铁 · 沧林食品", d:"", f:"cards/CF-02.html"},
    {e:"📄", n:"厚乳拿铁 · 沧林食品", d:"", f:"cards/CF-03.html"},
    {e:"📄", n:"陨石拿铁(黑糖珍珠) · 沧林食品", d:"", f:"cards/CF-04.html"},
    {e:"📄", n:"黑金气泡美式 CF-05 · 沧林食品", d:"", f:"cards/CF-05.html"},
    {e:"📄", n:"桂花拿铁 CF-06 · 沧林食品", d:"", f:"cards/CF-06.html"},
    {e:"📄", n:"燕麦拿铁 CF-07 · 沧林食品", d:"", f:"cards/CF-07.html"},
    {e:"📄", n:"椰青美式 CF-08 · 沧林食品", d:"", f:"cards/CF-08.html"},
  ],
  "🌶️ 经典名鸡": [
    {e:"📄", n:"椒麻鸡 · 完整产品卡 · 沧林食品工作站", d:"", f:"cards/椒麻鸡_产品卡.html"},
    {e:"📄", n:"椒麻鸡 · 完整工艺配方文档 · 沧林食品工作站", d:"", f:"cards/椒麻鸡_工艺配方文档.html"},
  ],
  "🌶️ 酱料系列": [
    {e:"📄", n:"JL-001 · 咔库秘制", d:"", f:"cards/JL_001.html"},
    {e:"📄", n:"蒜味茄汁意面酱 · 咔库秘制", d:"", f:"cards/JL_002.html"},
    {e:"📄", n:"红烩海鲜酱 · 咔库秘制", d:"", f:"cards/JL_003.html"},
    {e:"📄", n:"米酱 · 咔库秘制", d:"", f:"cards/JL_004.html"},
    {e:"📄", n:"BBQ烤肉酱 · 咔库秘制", d:"", f:"cards/JL_005.html"},
    {e:"📄", n:"麻酱面酱 · 咔库秘制", d:"", f:"cards/JL_006.html"},
    {e:"📄", n:"盐水鸡蘸酱(卤水) · 咔库秘制", d:"", f:"cards/JL_007.html"},
    {e:"📄", n:"意式肉酱 · 咔库秘制", d:"", f:"cards/JL_008.html"},
    {e:"📄", n:"新鲜番茄酱 · 咔库秘制", d:"", f:"cards/JL_009.html"},
    {e:"📄", n:"咖喱番茄酱 · 咔库秘制", d:"", f:"cards/JL_010.html"},
    {e:"📄", n:"橙汁排骨酱 · 咔库秘制", d:"", f:"cards/JL_011.html"},
    {e:"📄", n:"广东油鸡卤水 · 咔库秘制", d:"", f:"cards/JL_012.html"},
    {e:"📄", n:"低脂沙拉酱 · 咔库秘制", d:"", f:"cards/JL_013.html"},
    {e:"📄", n:"马铃薯沙拉(一) · 咔库秘制", d:"", f:"cards/JL_014.html"},
    {e:"📄", n:"蒜味烤肉酱 · 咔库秘制", d:"", f:"cards/JL_015.html"},
    {e:"📄", n:"马铃薯沙拉(二) · 咔库秘制", d:"", f:"cards/JL_016.html"},
    {e:"📄", n:"味噌烤肉酱 · 咔库秘制", d:"", f:"cards/JL_017.html"},
    {e:"📄", n:"天妇罗蘸酱 · 咔库秘制", d:"", f:"cards/JL_018.html"},
    {e:"📄", n:"腐乳腌酱(鸡排) · 咔库秘制", d:"", f:"cards/JL_019.html"},
    {e:"📄", n:"香柠腌汁(鸡排) · 咔库秘制", d:"", f:"cards/JL_020.html"},
    {e:"📄", n:"传统鸡排腌汁 · 咔库秘制", d:"", f:"cards/JL_021.html"},
    {e:"📄", n:"梅子酱 · 咔库秘制", d:"", f:"cards/JL_022.html"},
    {e:"📄", n:"蒜蓉酱 · 咔库秘制", d:"", f:"cards/JL_023.html"},
    {e:"📄", n:"甜辣酱 · 咔库秘制", d:"", f:"cards/JL_024.html"},
    {e:"📄", n:"炸酱面酱 · 咔库秘制", d:"", f:"cards/JL_025.html"},
    {e:"📄", n:"南瓜酱 · 咔库秘制", d:"", f:"cards/JL_026.html"},
    {e:"📄", n:"树子辣酱 · 咔库秘制", d:"", f:"cards/JL_027.html"},
    {e:"📄", n:"薄荷酱 · 咔库秘制", d:"", f:"cards/JL_028.html"},
    {e:"📄", n:"豆乳泥辣酱 · 咔库秘制", d:"", f:"cards/JL_029.html"},
    {e:"📄", n:"昆布酱 · 咔库秘制", d:"", f:"cards/JL_030.html"},
    {e:"📄", n:"蒸鱼梅子酱 · 咔库秘制", d:"", f:"cards/JL_031.html"},
    {e:"📄", n:"蘑菇酱 · 咔库秘制", d:"", f:"cards/JL_032.html"},
    {e:"📄", n:"酪梨酱 · 咔库秘制", d:"", f:"cards/JL_033.html"},
    {e:"📄", n:"鹅肉扁蘸酱 · 咔库秘制", d:"", f:"cards/JL_034.html"},
    {e:"📄", n:"炸鸡块酸辣酱 · 咔库秘制", d:"", f:"cards/JL_035.html"},
    {e:"📄", n:"关东煮蘸酱 · 咔库秘制", d:"", f:"cards/JL_036.html"},
    {e:"📄", n:"糖醋酱 · 咔库秘制", d:"", f:"cards/JL_037.html"},
    {e:"📄", n:"清蒸蟹虾蘸酱 · 咔库秘制", d:"", f:"cards/JL_038.html"},
    {e:"📄", n:"桂花酱 · 咔库秘制", d:"", f:"cards/JL_039.html"},
    {e:"📄", n:"日式照烧酱 · 咔库秘制", d:"", f:"cards/JL_040.html"},
    {e:"📄", n:"桑椹醋酱 · 咔库秘制", d:"", f:"cards/JL_041.html"},
    {e:"📄", n:"炸花枝蘸酱 · 咔库秘制", d:"", f:"cards/JL_042.html"},
    {e:"📄", n:"蚝油干面酱 · 咔库秘制", d:"", f:"cards/JL_043.html"},
    {e:"📄", n:"叉烧烤肉酱 · 咔库秘制", d:"", f:"cards/JL_044.html"},
    {e:"📄", n:"南洋风味烤肉酱 · 咔库秘制", d:"", f:"cards/JL_045.html"},
    {e:"📄", n:"羊肉炉蘸酱 · 咔库秘制", d:"", f:"cards/JL_046.html"},
    {e:"📄", n:"泰式酸醋酱 · 咔库秘制", d:"", f:"cards/JL_047.html"},
    {e:"📄", n:"贝类海鲜蘸酱 · 咔库秘制", d:"", f:"cards/JL_048.html"},
    {e:"📄", n:"红烧酱 · 咔库秘制", d:"", f:"cards/JL_049.html"},
    {e:"📄", n:"红油抄手酱 · 咔库秘制", d:"", f:"cards/JL_050.html"},
    {e:"（", n:"JL-051 韩式甜辣酱（熬制版）· 沧林食品", d:"", f:"cards/JL_051.html"},
    {e:"（", n:"JL-052 韩式嗨辣酱（爆辣）· 沧林食品", d:"", f:"cards/JL_052.html"},
    {e:"📄", n:"JL-053 韩式琥珀酱 · 沧林食品", d:"", f:"cards/JL_053.html"},
    {e:"（", n:"JL-054 蜂蜜芥末酱（沙拉酱版）· 沧林食品", d:"", f:"cards/JL_054.html"},
    {e:"📄", n:"JL-055 奶香芝士酱 · 沧林食品", d:"", f:"cards/JL_055.html"},
    {e:"📄", n:"JL-056 蒜香酱油酱 · 沧林食品", d:"", f:"cards/JL_056.html"},
    {e:"（", n:"JL-057 香辣酱（基础酱+辣椒油）· 沧林食品", d:"", f:"cards/JL_057.html"},
    {e:"📄", n:"JL-058 VC蜜汁酱 · 沧林食品", d:"", f:"cards/JL_058.html"},
    {e:"📄", n:"JL-059 糖醋蜜汁酱 · 沧林食品", d:"", f:"cards/JL_059.html"},
    {e:"📄", n:"JL-060 果味蜜汁酱 · 沧林食品", d:"", f:"cards/JL_060.html"},
    {e:"📄", n:"JL-061 调味酱油酱 · 沧林食品", d:"", f:"cards/JL_061.html"},
    {e:"📄", n:"JL-062 秘制辣椒油 · 沧林食品", d:"", f:"cards/JL_062.html"},
    {e:"📄", n:"JL-063 杰克丹尼酱 · 沧林食品", d:"", f:"cards/JL_063.html"},
    {e:"📄", n:"JL-064 四川炸鸡酱 · 沧林食品", d:"", f:"cards/JL_064.html"},
    {e:"📄", n:"JL-065 葱丝炸鸡酱 · 沧林食品", d:"", f:"cards/JL_065.html"},
    {e:"📄", n:"JL-066 米粉炸鸡蘸料 · 沧林食品", d:"", f:"cards/JL_066.html"},
    {e:"📄", n:"JL-067 蒜香炸鸡酱 · 沧林食品", d:"", f:"cards/JL_067.html"},
    {e:"📄", n:"JL-068 蜂蜜炸鸡酱 · 沧林食品", d:"", f:"cards/JL_068.html"},
    {e:"📄", n:"JL-069 椒香炸鸡酱 · 沧林食品", d:"", f:"cards/JL_069.html"},
    {e:"📄", n:"JL-070 辣炒炸鸡酱 · 沧林食品", d:"", f:"cards/JL_070.html"},
    {e:"（", n:"JL-071 酱油炸鸡酱（刷涂用） · 沧林食品", d:"", f:"cards/JL_071.html"},
    {e:"📄", n:"JL-072 秘酱炸鸡酱 · 沧林食品", d:"", f:"cards/JL_072.html"},
    {e:"📄", n:"JL-073 猕猴桃酱 · 沧林食品", d:"", f:"cards/JL_073.html"},
    {e:"（", n:"JL-074 伍斯特酱汁（自制） · 沧林食品", d:"", f:"cards/JL_074.html"},
    {e:"📄", n:"JL-075 黄芥末酸奶酱 · 沧林食品", d:"", f:"cards/JL_075.html"},
    {e:"（", n:"JL-076 韩式炸鸡基础酱（草莓酱版） · 沧林食品", d:"", f:"cards/JL_076.html"},
    {e:"（", n:"JL-077 蜂蜜芥末酱（简单版）· 沧林食品", d:"", f:"cards/JL_077.html"},
    {e:"📄", n:"JL-078 雪花柠檬酱 · 沧林食品", d:"", f:"cards/JL_078.html"},
    {e:"📄", n:"JL-079 芝士牛乳酱 · 沧林食品", d:"", f:"cards/JL_079.html"},
    {e:"📄", n:"JL-080 清爽蜂蜜柠檬蘸酱 · 沧林食品", d:"", f:"cards/JL_080.html"},
    {e:"📄", n:"JL-081 美式香草沙拉酱 · 沧林食品", d:"", f:"cards/JL_081.html"},
    {e:"📄", n:"JL-082 拌海螺酱料 · 沧林食品", d:"", f:"cards/JL_082.html"},
    {e:"📄", n:"JL-083 韩式辣白菜酱 · 沧林食品", d:"", f:"cards/JL_083.html"},
    {e:"📄", n:"JL-084 特甜酱 · 沧林食品", d:"", f:"cards/JL_084.html"},
    {e:"📄", n:"JL-085 石锅拌饭酱 · 沧林食品", d:"", f:"cards/JL_085.html"},
    {e:"📄", n:"JL-086 炸鸡拌饭汁 · 沧林食品", d:"", f:"cards/JL_086.html"},
  ],
  "🍃 经典名鸡": [
    {e:"📄", n:"茶香鸡 · 完整产品卡 · 沧林食品工作站", d:"", f:"cards/茶香鸡_产品卡.html"},
    {e:"🔒", n:"茶香鸡 · 完整工艺配方文档", d:"", f:"cards/茶香鸡_工艺配方文档.html"},
  ],
  "🍗 炸物系列": [
    {e:"📄", n:"咔库·秘制鸡锁骨 · 沧林食品", d:"", f:"cards/CS_001.html"},
    {e:"📄", n:"钵钵鸡红油 · 沧林食品", d:"", f:"cards/CS_002.html"},
    {e:"📄", n:"脆皮炸茄盒 · 沧林食品", d:"", f:"cards/CS_003.html"},
    {e:"📄", n:"港式叉烧酱 · 沧林食品", d:"", f:"cards/CS_004.html"},
    {e:"📄", n:"五香卤水 · 沧林食品", d:"", f:"cards/CS_005.html"},
  ],
  "🍗 炸鸡系列": [
    {e:"📄", n:"HZ-001 原味黄金炸鸡 · 沧林食品", d:"", f:"cards/HZ_001.html"},
    {e:"📄", n:"HZ-002 香辣/蒜香黄金炸鸡 · 沧林食品", d:"", f:"cards/HZ_002.html"},
    {e:"📄", n:"HZ-003 奥尔良黄金炸鸡 · 沧林食品", d:"", f:"cards/HZ_003.html"},
    {e:"📄", n:"HZ-004 韩式甜辣炸鸡 · 沧林食品", d:"", f:"cards/HZ_004.html"},
    {e:"📄", n:"HZ-005 蜂蜜芥末炸鸡 · 沧林食品", d:"", f:"cards/HZ_005.html"},
    {e:"📄", n:"HZ-006 琥珀酱油炸鸡 · 沧林食品", d:"", f:"cards/HZ_006.html"},
    {e:"📄", n:"HZ-007 奶香芝士炸鸡 / 脆皮芝士雪花炸鸡 · 沧林食品", d:"", f:"cards/HZ_007.html"},
    {e:"📄", n:"HZ-008 四川辣炒炸鸡 / 葱丝炸鸡 · 沧林食品", d:"", f:"cards/HZ_008.html"},
    {e:"📄", n:"HZ-009 咖喱炸鸡 / 咖喱鸡小腿 · 沧林食品", d:"", f:"cards/HZ_009.html"},
    {e:"（", n:"HZ-010 脆皮炸鸡（二次复炸）· 沧林食品", d:"", f:"cards/HZ_010.html"},
    {e:"📄", n:"HZ-011 米粉炸鸡 · 沧林食品", d:"", f:"cards/HZ_011.html"},
    {e:"📄", n:"HZ-012 蒜香黄金炸鸡 · 沧林食品", d:"", f:"cards/HZ_012.html"},
    {e:"📄", n:"HZ-013 原味黄金鸡翅中/翅根 · 沧林食品", d:"", f:"cards/HZ_013.html"},
    {e:"📄", n:"HZ-014 年糕无骨炸鸡 · 沧林食品", d:"", f:"cards/HZ_014.html"},
    {e:"（", n:"HZ-015 韩式蜜汁鸡块（6种口味）· 沧林食品", d:"", f:"cards/HZ_015.html"},
    {e:"📄", n:"HZ-016 调味酱油鸡块 · 沧林食品", d:"", f:"cards/HZ_016.html"},
    {e:"📄", n:"HZ-017 咖喱鸡小腿 · 沧林食品", d:"", f:"cards/HZ_017.html"},
    {e:"📄", n:"HZ-018 韩式起司棒棒鸡 · 沧林食品", d:"", f:"cards/HZ_018.html"},
    {e:"📄", n:"HZ-019 韩式炸鸡拌饭 / 韩式炸鸡大饭团 · 沧林食品", d:"", f:"cards/HZ_019.html"},
    {e:"（", n:"HZ-020 鸡腿汉堡（韩式炸鸡排堡）· 沧林食品", d:"", f:"cards/HZ_020.html"},
  ],
  "🍗 鸡排系列": [
    {e:"📄", n:"JP-01 香鸡排 · 沧林食品", d:"", f:"cards/JP_001.html"},
    {e:"📄", n:"JP-02 五香鸡排 · 沧林食品", d:"", f:"cards/JP_002.html"},
    {e:"📄", n:"JP-03 原味大鸡排 · 沧林食品", d:"", f:"cards/JP_003.html"},
    {e:"📄", n:"JP-04 沙茶大鸡排 · 沧林食品", d:"", f:"cards/JP_004.html"},
    {e:"📄", n:"JP-05 起司鸡排 · 沧林食品", d:"", f:"cards/JP_005.html"},
    {e:"📄", n:"JP-06 脆皮鸡排 · 沧林食品", d:"", f:"cards/JP_006.html"},
    {e:"📄", n:"JP-07 芝麻鸡排 · 沧林食品", d:"", f:"cards/JP_007.html"},
    {e:"📄", n:"JP-08 茄汁煎香草鸡排 · 沧林食品", d:"", f:"cards/JP_008.html"},
    {e:"📄", n:"JP-09 虾酱鸡排 · 沧林食品", d:"", f:"cards/JP_009.html"},
    {e:"📄", n:"JP-10 蜜汁鸡排 · 沧林食品", d:"", f:"cards/JP_010.html"},
    {e:"📄", n:"JP-11 茴味鸡排 · 沧林食品", d:"", f:"cards/JP_011.html"},
    {e:"📄", n:"JP-12 碳烤鸡排 · 沧林食品", d:"", f:"cards/JP_012.html"},
    {e:"📄", n:"JP-13 橙酱鸡排 · 沧林食品", d:"", f:"cards/JP_013.html"},
    {e:"📄", n:"JP-14 香草柠檬鸡排 · 沧林食品", d:"", f:"cards/JP_014.html"},
    {e:"📄", n:"JP-15 咖哩鸡排 · 沧林食品", d:"", f:"cards/JP_015.html"},
    {e:"📄", n:"JP-16 士林大鸡排 · 沧林食品", d:"", f:"cards/JP_016.html"},
    {e:"📄", n:"JP-17 泰式酸辣鸡排 · 沧林食品", d:"", f:"cards/JP_017.html"},
  ],
  "🍚 炒饭/拌菜": [
    {e:"📄", n:"馋嘴肉炒饭 · CZ-001 · 咔库秘制", d:"", f:"cards/CZ_001.html"},
    {e:"📄", n:"辣子鸡炒饭 · CZ-002 · 咔库秘制", d:"", f:"cards/CZ_002.html"},
    {e:"📄", n:"芝士酱油炒饭 · CZ-003 · 咔库秘制", d:"", f:"cards/CZ_003.html"},
    {e:"📄", n:"香辣肉酱炒饭 · CZ-004 · 咔库秘制", d:"", f:"cards/CZ_004.html"},
    {e:"📄", n:"拌牛肚 · 咔库秘制", d:"", f:"cards/CZ_005.html"},
    {e:"📄", n:"明太鱼干 · 产品卡 · 咔库秘制", d:"", f:"cards/CZ_006.html"},
    {e:"📄", n:"干泥鳅鱼 · 产品卡 · 咔库秘制", d:"", f:"cards/CZ_007.html"},
    {e:"📄", n:"苏子叶 · 咔库秘制", d:"", f:"cards/CZ_008.html"},
    {e:"📄", n:"酱小土豆 · 咔库秘制", d:"", f:"cards/CZ_009.html"},
    {e:"📄", n:"甜口牛板筋 · 咔库秘制", d:"", f:"cards/CZ_010.html"},
    {e:"（", n:"鲜族辣椒酱（甜口） · 咔库秘制", d:"", f:"cards/CZ_011.html"},
    {e:"📄", n:"拌干黄瓜片 · 咔库秘制", d:"", f:"cards/CZ_012.html"},
    {e:"📄", n:"干明太鱼丝 · 咔库秘制", d:"", f:"cards/CZ_013.html"},
    {e:"📄", n:"鲜族黄瓜妞 · 咔库秘制", d:"", f:"cards/CZ_014.html"},
    {e:"📄", n:"鲜族蒜茄子 · 咔库秘制", d:"", f:"cards/CZ_015.html"},
    {e:"📄", n:"鲜族甜细丝 · 咔库秘制", d:"", f:"cards/CZ_016.html"},
    {e:"📄", n:"拌介梗 · 咔库秘制", d:"", f:"cards/CZ_017.html"},
    {e:"📄", n:"CZ-018 · 鲜族萝卜丝 · 咔库秘制", d:"", f:"cards/CZ_018.html"},
    {e:"📄", n:"CZ-019 · 拌利子肉尖 · 咔库秘制", d:"", f:"cards/CZ_019.html"},
    {e:"📄", n:"CZ-020 · 拌蕨菜 · 咔库秘制", d:"", f:"cards/CZ_020.html"},
    {e:"📄", n:"CZ_021 · 拌牛肝 · 咔库秘制", d:"", f:"cards/CZ_021.html"},
    {e:"📄", n:"CZ_022 · 鱼子酱 · 咔库秘制", d:"", f:"cards/CZ_022.html"},
    {e:"📄", n:"CZ_023 · 五香干豆腐丝 · 咔库秘制", d:"", f:"cards/CZ_023.html"},
    {e:"📄", n:"CZ_024 · 小鱼花生 · 咔库秘制", d:"", f:"cards/CZ_024.html"},
    {e:"📄", n:"CZ_025 · 拌豆干拌素鸡 · 咔库秘制", d:"", f:"cards/CZ_025.html"},
    {e:"📄", n:"CZ_026 · 小银鱼干 · 咔库秘制", d:"", f:"cards/CZ_026.html"},
    {e:"📄", n:"CZ_027 · 萝卜块 · 咔库秘制", d:"", f:"cards/CZ_027.html"},
    {e:"📄", n:"CZ_028 · 拌五花菜 · 咔库秘制", d:"", f:"cards/CZ_028.html"},
    {e:"📄", n:"CZ_029 · 地瓜梗 · 咔库秘制", d:"", f:"cards/CZ_029.html"},
    {e:"📄", n:"CZ_030 · 鲜族甲鱼条 · 咔库秘制", d:"", f:"cards/CZ_030.html"},
    {e:"📄", n:"CZ_031 · 炒辣椒 · 咔库秘制", d:"", f:"cards/CZ_031.html"},
    {e:"📄", n:"CZ_032 · 干明太鱼皮 · 咔库秘制", d:"", f:"cards/CZ_032.html"},
    {e:"📄", n:"盖菜 · 沧林食品", d:"", f:"cards/CZ_033.html"},
    {e:"📄", n:"CZ_034 · 拌辣椒叶 · 咔库秘制", d:"", f:"cards/CZ_034.html"},
    {e:"📄", n:"小伙子萝卜 · 沧林食品", d:"", f:"cards/CZ_035.html"},
  ],
  "🍜 面食系列": [
    {e:"📄", n:"LM-001 安徽牛肉板面 · 沧林食品", d:"", f:"cards/LM_001.html"},
  ],
  "🍢 摆摊小吃": [
    {e:"📄", n:"美式炸薯条 · 沧林食品", d:"", f:"cards/XC_001.html"},
    {e:"📄", n:"台湾甘梅地瓜 · 沧林食品", d:"", f:"cards/XC_002.html"},
    {e:"📄", n:"黄金洋葱圈 · 沧林食品", d:"", f:"cards/XC_003.html"},
    {e:"📄", n:"黄金香蕉棒 · 沧林食品", d:"", f:"cards/XC_004.html"},
    {e:"📄", n:"葱香茄子饼 · 沧林食品", d:"", f:"cards/XC_005.html"},
    {e:"📄", n:"炸年糕 · 沧林食品", d:"", f:"cards/XC_006.html"},
    {e:"📄", n:"炸蔬菜拼盘 · 沧林食品", d:"", f:"cards/XC_007.html"},
    {e:"📄", n:"蝴蝶炸虾 · 沧林食品", d:"", f:"cards/XC_008.html"},
    {e:"📄", n:"酥脆鸡柳 · 沧林食品", d:"", f:"cards/XC_009.html"},
    {e:"（", n:"蝴蝶虾（简化版） · 沧林食品", d:"", f:"cards/XC_010.html"},
    {e:"📄", n:"XC_011 麻辣炒螺蛳 · 沧林食品", d:"", f:"cards/XC_011.html"},
    {e:"📄", n:"长沙臭豆腐 · 沧林食品", d:"", f:"cards/XC_013.html"},
    {e:"📄", n:"无矾油条 · 沧林食品", d:"", f:"cards/XC_014.html"},
    {e:"📄", n:"黄豆糍粑 · 沧林食品", d:"", f:"cards/XC_016.html"},
    {e:"📄", n:"鸡蛋仔 · 沧林食品", d:"", f:"cards/XC_017.html"},
  ],
  "🍧 糖水系列": [
    {e:"（", n:"TS-001 冰糖水（玫瑰/茉莉白桃） · 糖水铺", d:"", f:"cards/TS_001.html"},
    {e:"（", n:"TS-002 草莓糖水（草莓酸奶冰沙） · 糖水铺", d:"", f:"cards/TS_002.html"},
    {e:"📄", n:"TS-003 菠萝冰糖水 · 糖水铺", d:"", f:"cards/TS_003.html"},
    {e:"📄", n:"TS-004 菠萝糖水 · 糖水铺", d:"", f:"cards/TS_004.html"},
    {e:"📄", n:"TS-005 西瓜冰糖水 · 糖水铺", d:"", f:"cards/TS_005.html"},
    {e:"📄", n:"TS-006 红豆莲子百合糖水 · 糖水铺", d:"", f:"cards/TS_006.html"},
    {e:"📄", n:"TS-007 手工冰粉 · 糖水铺", d:"", f:"cards/TS_007.html"},
    {e:"📄", n:"TS-008 烧仙草冻 · 糖水铺", d:"", f:"cards/TS_008.html"},
    {e:"（", n:"TS-009 烧仙草冻（深褐色） · 糖水铺", d:"", f:"cards/TS_009.html"},
    {e:"📄", n:"TS-010 双皮奶 · 糖水铺", d:"", f:"cards/TS_010.html"},
    {e:"（", n:"TS-011 夜市甜饮（桂花甜饮） · 糖水铺", d:"", f:"cards/TS_011.html"},
    {e:"（", n:"TS-012 海南灵魂甜品（椰奶清补凉） · 糖水铺", d:"", f:"cards/TS_012.html"},
    {e:"📄", n:"TS-013 海底椰糖水 · 糖水铺", d:"", f:"cards/TS_013.html"},
    {e:"（", n:"TS-014 藕粉（桂花藕粉） · 糖水铺", d:"", f:"cards/TS_014.html"},
    {e:"📄", n:"TS-015 米酒小汤圆 · 糖水铺", d:"", f:"cards/TS_015.html"},
    {e:"📄", n:"TS-016 雪燕桃胶 · 糖水铺", d:"", f:"cards/TS_016.html"},
    {e:"📄", n:"TS-017 菠萝米酒 · 糖水铺", d:"", f:"cards/TS_017.html"},
    {e:"（", n:"TS-018 芒果西柚糖水（杨枝甘露风） · 糖水铺", d:"", f:"cards/TS_018.html"},
    {e:"📄", n:"TS-019 芋头芋圆椰奶 · 糖水铺", d:"", f:"cards/TS_019.html"},
    {e:"📄", n:"TS-020 椰奶西米露 · 糖水铺", d:"", f:"cards/TS_020.html"},
    {e:"（", n:"TS-021 拉丝酸奶（原味/果味） · 糖水铺", d:"", f:"cards/TS_021.html"},
    {e:"📄", n:"TS-022 炭烧拉丝酸奶 · 糖水铺", d:"", f:"cards/TS_022.html"},
      {e:"📄", n:"水果绵绵冰 · 沧林食品", d:"", f:"cards/XC_018.html"},
],
  "🍮 甜品系列": [
    {e:"📄", n:"TP-01 · 沧林食品", d:"", f:"cards/TP-01.html"},
    {e:"📄", n:"红糖糍粑冰粉 · 沧林食品", d:"", f:"cards/TP-02.html"},
    {e:"📄", n:"芋圆冰粉 · 沧林食品", d:"", f:"cards/TP-03.html"},
    {e:"📄", n:"杨枝甘露 · 沧林食品", d:"", f:"cards/TP-04.html"},
    {e:"📄", n:"烧仙草 · 沧林食品", d:"", f:"cards/TP-05.html"},
    {e:"📄", n:"芒果双皮奶 · 沧林食品", d:"", f:"cards/TP-06.html"},
    {e:"📄", n:"椰奶西米露 · 沧林食品", d:"", f:"cards/TP-07.html"},
    {e:"📄", n:"TP-08 · 豆花布丁 · 沧林食品", d:"", f:"cards/TP-08.html"},
      {e:"📄", n:"奥利奥双皮奶 · 沧林食品", d:"", f:"cards/XC_015.html"},
],
  "🍱 日式系列": [
    {e:"📄", n:"RB-002 · 沧林食品", d:"", f:"cards/RB_002.html"},
    {e:"📄", n:"RB-003 · 沧林食品", d:"", f:"cards/RB_003.html"},
    {e:"📄", n:"RB-004 · 沧林食品", d:"", f:"cards/RB_004.html"},
    {e:"📄", n:"RB-005 · 沧林食品", d:"", f:"cards/RB_005.html"},
    {e:"📄", n:"RB-006 · 沧林食品", d:"", f:"cards/RB_006.html"},
    {e:"📄", n:"RB-007 · 沧林食品", d:"", f:"cards/RB_007.html"},
    {e:"📄", n:"RB-008 · 沧林食品", d:"", f:"cards/RB_008.html"},
  ],
  "🍲 汤料卤水": [
    {e:"📄", n:"TL-019 牛肉板面浇头 · 沧林食品", d:"", f:"cards/TL_019.html"},
  ],
  "🏪 门店运营": [
    {e:"📄", n:"灌汤包 · 门店运营卡 · M1 · 沧林食品", d:"", f:"cards/MD_BZ_001_灌汤包门店运营版.html"},
    {e:"📄", n:"开封桶子鸡 · 门店运营卡 · M1 · 沧林食品", d:"", f:"cards/MD_LW_001_桶子鸡门店运营版.html"},
    {e:"：", n:"门店运营卡 · M1", d:"", f:"cards/store-card-m1.html"},
  ],
  "🏮 经典名鸡": [
    {e:"📄", n:"道口烧鸡 · 酱卤工艺卡 · 沧林食品工作站", d:"", f:"cards/daokou-shaoji.html"},
  ],
  "🏺 经典名鸡": [
    {e:"（", n:"叫花鸡（郑州版）· 完整产品卡 · 沧林食品工作站", d:"", f:"cards/叫花鸡_郑州版_产品卡.html"},
    {e:"（", n:"叫花鸡（郑州版）· 完整工艺配方文档 · 沧林食品工作站", d:"", f:"cards/叫花鸡_郑州版_工艺配方文档.html"},
  ],
  "🐓 经典名鸡": [
    {e:"⚠", n:"开封桶子鸡 · 完整产品卡 · 沧林食品工作站", d:"", f:"cards/桶子鸡_产品卡.html"},
    {e:"📄", n:"开封桶子鸡 · 完整工艺配方文档 · 沧林食品工作站", d:"", f:"cards/桶子鸡_配方文档.html"},
  ],
  "📂 其他": [
    {e:"📄", n:"串串香底料 · 沧林食品", d:"", f:"cards/串串香底料.html"},
    {e:"📄", n:"YL-011 冰糖酸梅汤 · 沧林食品", d:"", f:"cards/冰糖酸梅汤.html"},
    {e:"📄", n:"剁椒酱 · 沧林食品", d:"", f:"cards/剁椒酱.html"},
    {e:"📄", n:"发面金丝饼 · 沧林食品", d:"", f:"cards/发面金丝饼.html"},
    {e:"📄", n:"地锅鸡酱料 · 沧林食品", d:"", f:"cards/地锅鸡酱料.html"},
    {e:"📄", n:"LM-001 安徽牛肉板面 · 沧林食品", d:"", f:"cards/安徽牛肉板面.html"},
    {e:"📄", n:"川式五香卤水 · 沧林食品", d:"", f:"cards/川式五香卤水.html"},
    {e:"📄", n:"枣花馒头 · 沧林食品", d:"", f:"cards/枣花馒头.html"},
    {e:"📄", n:"烧鸡卤水 · 沧林食品", d:"", f:"cards/烧鸡卤水.html"},
    {e:"📄", n:"独一味油饼 · 沧林食品", d:"", f:"cards/独一味油饼.html"},
    {e:"📄", n:"XC_012 秘制钵钵鸡 · 沧林食品", d:"", f:"cards/秘制钵钵鸡.html"},
    {e:"📄", n:"脆皮五花肉 · 沧林食品", d:"", f:"cards/脆皮五花肉.html"},
    {e:"📄", n:"重庆鸡公煲酱料 · 沧林食品", d:"", f:"cards/重庆鸡公煲酱料.html"},
    {e:"📄", n:"重庆麻辣烤鱼酱 · 沧林食品", d:"", f:"cards/重庆麻辣烤鱼酱.html"},
    {e:"📄", n:"XC_011 麻辣炒螺蛳 · 沧林食品", d:"", f:"cards/麻辣炒螺蛳.html"},
  ],
  "🔥 经典名鸡": [
    {e:"📄", n:"沟帮子熏鸡 · 完整产品卡 · 沧林食品工作站", d:"", f:"cards/沟帮子熏鸡_商业产品卡.html"},
  ],
  "🥗 冷吃系列": [
    {e:"📄", n:"冷吃麻辣鸡爪 · 沧林食品", d:"", f:"cards/LB_001.html"},
    {e:"📄", n:"冷吃麻辣鸭头 · 沧林食品", d:"", f:"cards/LB_002.html"},
    {e:"📄", n:"冷吃卤藕片 · 沧林食品", d:"", f:"cards/LB_003.html"},
    {e:"📄", n:"冷吃拌鸡架 · 沧林食品", d:"", f:"cards/LB_004.html"},
    {e:"📄", n:"冷吃红油拌猪头肉 · 沧林食品", d:"", f:"cards/LB_005.html"},
  ],
  "🥟 包子系列": [
    {e:"📄", n:"灌汤包 · 沧林食品", d:"", f:"cards/BZ_001.html"},
    {e:"📄", n:"龙眼汤包 · 沧林食品", d:"", f:"cards/BZ_002.html"},
    {e:"📄", n:"馨香猪肉灌汤包 · 沧林食品", d:"", f:"cards/BZ_003.html"},
    {e:"📄", n:"开封猪肉灌汤包 · 咔库秘制", d:"", f:"cards/BZ_004.html"},
    {e:"📄", n:"草菇蔬菜汤包 · 沧林食品", d:"", f:"cards/BZ_005.html"},
    {e:"📄", n:"长沙清香猪肉灌汤包 · 咔库秘制", d:"", f:"cards/BZ_007.html"},
    {e:"📄", n:"酸奶玉米灌汤包 · 咔库秘制", d:"", f:"cards/BZ_008.html"},
    {e:"📄", n:"鸭肉灌汤包 · 咔库秘制", d:"", f:"cards/BZ_009.html"},
    {e:"📄", n:"BZ-01 淮扬蟹黄汤包 · 沧林食品", d:"", f:"cards/BZ_01.html"},
    {e:"📄", n:"杭州猪肉小笼包 · 咔库秘制", d:"", f:"cards/BZ_010.html"},
    {e:"📄", n:"上海猪肉小笼包 · 咔库秘制", d:"", f:"cards/BZ_011.html"},
    {e:"📄", n:"BZ-012 菇鳝小笼包 · 咔库秘制", d:"", f:"cards/BZ_012.html"},
    {e:"（", n:"BZ-013 猪肉灌汤包（第一种）· 咔库秘制", d:"", f:"cards/BZ_013.html"},
    {e:"📄", n:"BZ-014 猪肉灌汤包 · 咔库秘制", d:"", f:"cards/BZ_014.html"},
    {e:"📄", n:"BZ-015 鸡肉灌汤包 · 咔库秘制", d:"", f:"cards/BZ_015.html"},
    {e:"📄", n:"BZ-016 鸡汁肉包 · 咔库秘制", d:"", f:"cards/BZ_016.html"},
    {e:"📄", n:"BZ-017 素三鲜包 · 咔库秘制", d:"", f:"cards/BZ_017.html"},
    {e:"📄", n:"BZ-018 麻辣素包 · 咔库秘制", d:"", f:"cards/BZ_018.html"},
    {e:"📄", n:"BZ-019 梅菜肉包 · 咔库秘制", d:"", f:"cards/BZ_019.html"},
    {e:"📄", n:"BZ-02 猪肉包子 · 沧林食品", d:"", f:"cards/BZ_02.html"},
    {e:"📄", n:"BZ-020 芹菜肉包 · 咔库秘制", d:"", f:"cards/BZ_020.html"},
    {e:"📄", n:"BZ-021 鲜葱肉包 · 咔库秘制", d:"", f:"cards/BZ_021.html"},
    {e:"📄", n:"BZ-022 香菇肉包 · 咔库秘制", d:"", f:"cards/BZ_022.html"},
    {e:"📄", n:"BZ-023 豇豆肉包 · 咔库秘制", d:"", f:"cards/BZ_023.html"},
    {e:"📄", n:"BZ-024 包子专用料油 · 咔库秘制", d:"", f:"cards/BZ_024.html"},
    {e:"📄", n:"BZ-025 包子通用和面配方 · 咔库秘制", d:"", f:"cards/BZ_025.html"},
    {e:"📄", n:"BZ-03 酱肉包子 · 沧林食品", d:"", f:"cards/BZ_03.html"},
    {e:"📄", n:"BZ-04 咖喱牛肉包子 · 沧林食品", d:"", f:"cards/BZ_04.html"},
    {e:"📄", n:"BZ-05 香菇青菜包子 · 沧林食品", d:"", f:"cards/BZ_05.html"},
    {e:"📄", n:"BZ-06 玫瑰豆沙包 · 沧林食品", d:"", f:"cards/BZ_06.html"},
    {e:"📄", n:"BZ-07 麻辣粉丝包 · 沧林食品", d:"", f:"cards/BZ_07.html"},
    {e:"📄", n:"灌汤包 · 门店版 · FoodIntel AI", d:"", f:"cards/BZ_S001.html"},
  ],
  "🥟 早餐系列": [
    {e:"📄", n:"ZC-01 皮蛋瘦肉粥 · 沧林食品", d:"", f:"cards/ZC_01.html"},
    {e:"📄", n:"ZC-02 南瓜粥 · 沧林食品", d:"", f:"cards/ZC_02.html"},
    {e:"📄", n:"ZC-03 小米粥 · 沧林食品", d:"", f:"cards/ZC_03.html"},
    {e:"📄", n:"ZC-04 千层饼 · 沧林食品", d:"", f:"cards/ZC_04.html"},
    {e:"📄", n:"ZC-05 葱香鸡蛋饼 · 沧林食品", d:"", f:"cards/ZC_05.html"},
    {e:"📄", n:"ZC-06 京东肉饼 · 沧林食品", d:"", f:"cards/ZC_06.html"},
    {e:"📄", n:"ZC-07 糍粑油条 · 沧林食品", d:"", f:"cards/ZC_07.html"},
    {e:"📄", n:"ZC-08 菜角 · 沧林食品", d:"", f:"cards/ZC_08.html"},
    {e:"📄", n:"ZC-09 武汉三鲜豆皮 · 沧林食品", d:"", f:"cards/ZC_09.html"},
  ],
  "🥡 预制半成品": [
    {e:"📄", n:"日式烧鸟·京葱鸡肉串 · 沧林食品", d:"", f:"cards/YB_001.html"},
    {e:"📄", n:"日式烧鸟·鸡皮串 · 沧林食品", d:"", f:"cards/YB_002.html"},
    {e:"📄", n:"日式烧鸟·鸡软骨串 · 沧林食品", d:"", f:"cards/YB_003.html"},
    {e:"📄", n:"日式烧鸟·烤鸡翅 · 沧林食品", d:"", f:"cards/YB_004.html"},
    {e:"📄", n:"日式烧鸟·和牛横膈膜 · 沧林食品", d:"", f:"cards/YB_005.html"},
    {e:"📄", n:"日式照烧酱 · 沧林食品", d:"", f:"cards/YB_006.html"},
  ],
  "🥢 傣舂系列": [
    {e:"📄", n:"傣味舂鸡脚 · 咔库秘制", d:"", f:"cards/DC_001.html"},
    {e:"📄", n:"傣味舂鸡腿 · 咔库秘制", d:"", f:"cards/DC_002.html"},
    {e:"📄", n:"傣味舂鱿鱼 · 咔库秘制", d:"", f:"cards/DC_003.html"},
    {e:"📄", n:"傣味舂大虾 · 咔库秘制", d:"", f:"cards/DC_004.html"},
    {e:"📄", n:"傣味舂菠萝 · 咔库秘制", d:"", f:"cards/DC_005.html"},
    {e:"📄", n:"味味舂黄瓜 · 咔库秘制", d:"", f:"cards/DC_006.html"},
    {e:"📄", n:"味味舂木瓜 · 咔库秘制", d:"", f:"cards/DC_007.html"},
    {e:"📄", n:"傣味舂洋芋 · 咔库秘制", d:"", f:"cards/DC_008.html"},
    {e:"📄", n:"傣味舂油豆腐 · 咔库秘制", d:"", f:"cards/DC_009.html"},
    {e:"📄", n:"味味舂海带 · 咔库秘制", d:"", f:"cards/DC_010.html"},
    {e:"📄", n:"傣味舂米线 · 咔库秘制", d:"", f:"cards/DC_011.html"},
    {e:"📄", n:"味味舂泡面 · 咔库秘制", d:"", f:"cards/DC_012.html"},
  ],
  "🥣 粥品系列": [
    {e:"📄", n:"皮蛋瘦肉粥 · 产品卡 · 咔库秘制", d:"", f:"cards/ZS_001.html"},
    {e:"📄", n:"蔬菜素粥 · 咔库秘制", d:"", f:"cards/ZS_002.html"},
    {e:"📄", n:"ZS-003 滑蛋牛肉粥 · 沧林食品", d:"", f:"cards/ZS_003.html"},
    {e:"📄", n:"ZS-004 八宝黑米粥 · 咔库秘制", d:"", f:"cards/ZS_004.html"},
    {e:"📄", n:"ZS-005 黑芝麻糙米粥 · 咔库秘制", d:"", f:"cards/ZS_005.html"},
    {e:"📄", n:"ZS-006 山药萝卜粥 · 咔库秘制", d:"", f:"cards/ZS_006.html"},
    {e:"📄", n:"ZS-007 苹果粥 · 咔库秘制", d:"", f:"cards/ZS_007.html"},
    {e:"📄", n:"ZS-008 山楂粥 · 咔库秘制", d:"", f:"cards/ZS_008.html"},
    {e:"📄", n:"ZS-009 豆浆粥 · 咔库秘制", d:"", f:"cards/ZS_009.html"},
    {e:"📄", n:"ZS-010 山药枸杞粥 · 咔库秘制", d:"", f:"cards/ZS_010.html"},
    {e:"📄", n:"海带绿豆粥 · 沧林食品", d:"", f:"cards/ZS_011.html"},
    {e:"📄", n:"鸡肉粥 · 沧林食品", d:"", f:"cards/ZS_012.html"},
    {e:"📄", n:"胡萝卜甜粥 · 沧林食品", d:"", f:"cards/ZS_013.html"},
    {e:"📄", n:"肉末菜粥 · 咔库秘制", d:"", f:"cards/ZS_014.html"},
    {e:"📄", n:"南瓜牛奶粥 · 咔库秘制", d:"", f:"cards/ZS_015.html"},
    {e:"📄", n:"桂圆莲子粥 · 咔库秘制", d:"", f:"cards/ZS_016.html"},
    {e:"📄", n:"紫米粥 · 咔库秘制", d:"", f:"cards/ZS_017.html"},
    {e:"📄", n:"麦片粥 · 咔库秘制", d:"", f:"cards/ZS_018.html"},
    {e:"📄", n:"小米粥 · 咔库秘制", d:"", f:"cards/ZS_019.html"},
    {e:"📄", n:"清粥 · 咔库秘制", d:"", f:"cards/ZS_020.html"},
    {e:"📄", n:"鸡丝玉米粥 · 咔库秘制", d:"", f:"cards/ZS_021.html"},
    {e:"📄", n:"芝麻核桃粥 · 咔库秘制", d:"", f:"cards/ZS_022.html"},
    {e:"📄", n:"苦瓜粥 · 咔库秘制", d:"", f:"cards/ZS_023.html"},
    {e:"📄", n:"鱼片粥 · 咔库秘制", d:"", f:"cards/ZS_024.html"},
    {e:"📄", n:"嫩南瓜粥 · 咔库秘制", d:"", f:"cards/ZS_025.html"},
    {e:"📄", n:"猪肝鸡蛋粥 · 咔库秘制", d:"", f:"cards/ZS_026.html"},
    {e:"📄", n:"香菇瘦肉粥 · 咔库秘制", d:"", f:"cards/ZS_027.html"},
    {e:"📄", n:"窝蛋牛肉粥 · 咔库秘制", d:"", f:"cards/ZS_028.html"},
    {e:"📄", n:"鲜菇海鲜粥 · 咔库秘制", d:"", f:"cards/ZS_029.html"},
    {e:"📄", n:"芋头香菇瘦肉粥 · 咔库秘制", d:"", f:"cards/ZS_030.html"},
    {e:"📄", n:"泉州蚝仔粥 · 咔库秘制", d:"", f:"cards/ZS_031.html"},
    {e:"📄", n:"紫薯燕麦粥 · 咔库秘制", d:"", f:"cards/ZS_032.html"},
    {e:"📄", n:"南瓜粥 · 咔库秘制", d:"", f:"cards/ZS_033.html"},
    {e:"📄", n:"排骨皮蛋粥 · 咔库秘制", d:"", f:"cards/ZS_034.html"},
  ],
  "🫕 火锅酸汤": [
    {e:"📄", n:"凯里酸汤鱼（摆摊版） · 咔库秘制", d:"", f:"cards/HG_001.html"},
    {e:"📄", n:"麻辣串串香（摆摊版） · 咔库秘制", d:"", f:"cards/HG_002.html"},
    {e:"📄", n:"酸辣粉/冒菜（摆摊版） · 咔库秘制", d:"", f:"cards/HG_003.html"},
  ],
  "🍳 炒饭炒面花甲": [
    {e:"📄", n:"馋嘴肉炒饭 · 咔库秘制", d:"", f:"cards/CF_001.html"},
    {e:"📄", n:"孜然炒面 · 咔库秘制", d:"", f:"cards/CF_002.html"},
    {e:"📄", n:"香辣炒花甲 · 咔库秘制", d:"", f:"cards/CF_003.html"},
    {e:"📄", n:"蒜香炒虾尾 · 咔库秘制", d:"", f:"cards/CF_004.html"},
    {e:"📄", n:"香辣炒螺丝 · 咔库秘制", d:"", f:"cards/CF_005.html"},
    {e:"📄", n:"黑椒牛扒饭 · 咔库秘制", d:"", f:"cards/CF_006.html"},
    {e:"📄", n:"腊味煲仔饭 · 咔库秘制", d:"", f:"cards/CF_007.html"},
  ],
  "🍜 粉面系列": [
    {e:"📄", n:"正宗柳州螺蛳粉 · 咔库秘制", d:"", f:"cards/FM_001.html"},
    {e:"📄", n:"武汉热干面 · 咔库秘制", d:"", f:"cards/FM_002.html"},
    {e:"📄", n:"长沙牛肉粉 · 咔库秘制", d:"", f:"cards/FM_003.html"},
    {e:"📄", n:"成都担担面 · 咔库秘制", d:"", f:"cards/FM_004.html"},
    {e:"📄", n:"淮南牛肉汤粉 · 咔库秘制", d:"", f:"cards/FM_005.html"},
  ],
  "🥣 胡辣汤": [
    {e:"📄", n:"经典河南糊辣汤 · 咔库秘制", d:"", f:"cards/HLT_001.html"},
    {e:"📄", n:"逍遥镇羊肉胡辣汤 · 咔库秘制", d:"", f:"cards/HLT_002.html"},
    {e:"📄", n:"逍遥镇肉丁胡辣汤 · 咔库秘制", d:"", f:"cards/HLT_003.html"},
    {e:"📄", n:"逍遥镇面筋胡辣汤 · 咔库秘制", d:"", f:"cards/HLT_004.html"},
    {e:"📄", n:"胡辣汤专用大料粉 · 咔库秘制", d:"", f:"cards/HLT_005.html"},
  ],
  "🍗 卤炸帮": [
    {e:"📄", n:"川香辣卤整体方案 · 咔库秘制", d:"", f:"cards/LZ_000.html"},
    {e:"📄", n:"卤炸帮 · 鸭货系列 · 咔库秘制", d:"", f:"cards/LZ_001.html"},
    {e:"📄", n:"卤炸帮 · 鸡货系列 · 咔库秘制", d:"", f:"cards/LZ_002.html"},
    {e:"📄", n:"卤炸帮 · 猪货系列 · 咔库秘制", d:"", f:"cards/LZ_003.html"},
    {e:"📄", n:"卤炸帮 · 牛货系列 · 咔库秘制", d:"", f:"cards/LZ_004.html"},
    {e:"📄", n:"卤炸帮 · 羊货系列 · 咔库秘制", d:"", f:"cards/LZ_005.html"},
    {e:"📄", n:"卤炸帮 · 素菜系列 · 咔库秘制", d:"", f:"cards/LZ_006.html"},
  ],
  "🥤 手打柠檬茶": [
    {e:"📄", n:"招牌手打柠檬茶 · 沧林食品", d:"", f:"cards/CD_009.html"},
    {e:"📄", n:"泰绿柠檬茶 · 沧林食品", d:"", f:"cards/CD_010.html"},
    {e:"📄", n:"苦瓜柠檬茶 · 沧林食品", d:"", f:"cards/CD_011.html"},
    {e:"📄", n:"青瓜柠檬茶 · 沧林食品", d:"", f:"cards/CD_012.html"},
    {e:"📄", n:"杨梅柠檬茶 · 沧林食品", d:"", f:"cards/CD_013.html"},
    {e:"📄", n:"芭乐柠檬茶 · 沧林食品", d:"", f:"cards/CD_014.html"},
    {e:"📄", n:"凤梨冰柠茶 · 沧林食品", d:"", f:"cards/CD_015.html"},
    {e:"📄", n:"草莓冰柠茶 · 沧林食品", d:"", f:"cards/CD_016.html"},
    {e:"📄", n:"芒果柠檬茶 · 沧林食品", d:"", f:"cards/CD_017.html"},
    {e:"📄", n:"西瓜柠檬茶 · 沧林食品", d:"", f:"cards/CD_018.html"},
    {e:"📄", n:"桂花柠檬茶 · 沧林食品", d:"", f:"cards/CD_019.html"},
    {e:"📄", n:"陈皮柠檬茶 · 沧林食品", d:"", f:"cards/CD_020.html"},
    {e:"📄", n:"CD-021 话梅柠檬茶 · 沧林食品", d:"", f:"cards/CD_021.html"},
    {e:"📄", n:"百香果柠檬茶 · 沧林食品", d:"", f:"cards/CD_022.html"},
    {e:"📄", n:"鸭屎香柠檬茶 · 沧林食品", d:"", f:"cards/CD_023.html"},
    {e:"📄", n:"海底椰柠檬茶 · 沧林食品", d:"", f:"cards/CD_024.html"},
    {e:"📄", n:"港式冻柠茶 · 沧林食品", d:"", f:"cards/CD_025.html"},
    {e:"📄", n:"蜂蜜柠檬茶 · 沧林食品", d:"", f:"cards/CD_026.html"},
    {e:"📄", n:"CD-027 特浓手打柠檬茶 · 沧林食品", d:"", f:"cards/CD_027.html"},
    {e:"📄", n:"CD-028 特浓咸Darling · 沧林食品", d:"", f:"cards/CD_028.html"},
    {e:"（", n:"CD-029 特浓啡柠（咖啡柠檬茶） · 沧林食品", d:"", f:"cards/CD_029.html"},
    {e:"📄", n:"CD-030 绿妍手打柠檬茶 · 沧林食品", d:"", f:"cards/CD_030.html"},
    {e:"📄", n:"CD-031 一颗柠檬绿茶 · 沧林食品", d:"", f:"cards/CD_031.html"},
    {e:"📄", n:"CD-032 苦瓜椰柠冰茶 · 沧林食品", d:"", f:"cards/CD_032.html"},
    {e:"📄", n:"CD-033 葡萄冰柠茶 · 沧林食品", d:"", f:"cards/CD_033.html"},
    {e:"📄", n:"CD-034 奇异果冰柠茶 · 沧林食品", d:"", f:"cards/CD_034.html"},
    {e:"📄", n:"CD-035 芭乐柠檬茶 · 沧林食品", d:"", f:"cards/CD_035.html"},
    {e:"📄", n:"CD-036 芒果柠檬茶 · 沧林食品", d:"", f:"cards/CD_036.html"},
    {e:"📄", n:"CD-037 羊角蜜柠檬茶 · 沧林食品", d:"", f:"cards/CD_037.html"},
    {e:"（", n:"CD-038 黄皮柠檬茶（夏日甜/秋之盐） · 沧林食品", d:"", f:"cards/CD_038.html"},
    {e:"（", n:"CD-039 草莓长岛冰茶（无柠檬柠檬茶） · 沧林食品", d:"", f:"cards/CD_039.html"},
    {e:"📄", n:"CD-040 糯香柠檬茶 · 沧林食品", d:"", f:"cards/CD_040.html"},
    {e:"📄", n:"山茶花柠檬茶 · 沧林食品", d:"", f:"cards/CD_041.html"},
    {e:"📄", n:"桃桃乌龙柠檬茶 · 沧林食品", d:"", f:"cards/CD_042.html"},
    {e:"📄", n:"蜜桃乌龙茶 · 沧林食品", d:"", f:"cards/CD_043.html"},
    {e:"📄", n:"杨梅柠檬茶 · 沧林食品", d:"", f:"cards/CD_044.html"},
    {e:"📄", n:"甜橙冰柠茶 · 沧林食品", d:"", f:"cards/CD_045.html"},
    {e:"📄", n:"橙多芬冰柠茶 · 沧林食品", d:"", f:"cards/CD_046.html"},
    {e:"📄", n:"春见柑冰柠茶 · 沧林食品", d:"", f:"cards/CD_047.html"},
    {e:"📄", n:"招牌霸王杯 · 沧林食品", d:"", f:"cards/CD_048.html"},
    {e:"📄", n:"鸭屎香霸王杯 · 沧林食品", d:"", f:"cards/CD_049.html"},
    {e:"📄", n:"霸霸水果茶 · 沧林食品", d:"", f:"cards/CD_050.html"},
    {e:"📄", n:"摘牌柠檬霸王杯 · 沧林食品", d:"", f:"cards/CD_051.html"},
    {e:"📄", n:"西瓜海底椰霸王杯 · 沧林食品", d:"", f:"cards/CD_052.html"},
    {e:"📄", n:"凤梨霸王杯 · 沧林食品", d:"", f:"cards/CD_053.html"},
    {e:"📄", n:"西瓜凤梨鲜果茶 · 沧林食品", d:"", f:"cards/CD_054.html"},
    {e:"📄", n:"斑斓柠檬茶 · 沧林食品", d:"", f:"cards/CD_055.html"},
  ],
  "🥤 饮品系列": [
    {e:"📄", n:"芝芝莓莓 · 沧林食品", d:"", f:"cards/YL_001.html"},
    {e:"📄", n:"莓莓奶冻 · 沧林食品", d:"", f:"cards/YL_002.html"},
    {e:"📄", n:"霸气莓莓脆啵啵 · 沧林食品", d:"", f:"cards/YL_003.html"},
    {e:"📄", n:"草莓小丸子 · 沧林食品", d:"", f:"cards/YL_004.html"},
    {e:"📄", n:"草莓桃桃茶 · 沧林食品", d:"", f:"cards/YL_005.html"},
    {e:"📄", n:"生椰可可冰茶 · 沧林食品", d:"", f:"cards/YL_006.html"},
    {e:"📄", n:"椰子三兄弟 · 沧林食品", d:"", f:"cards/YL_007.html"},
    {e:"📄", n:"超浓郁椰丸黑芝麻 · 沧林食品", d:"", f:"cards/YL_008.html"},
    {e:"📄", n:"清补凉 · 沧林食品", d:"", f:"cards/YL_009.html"},
    {e:"📄", n:"杨枝甘露 · 沧林食品", d:"", f:"cards/YL_010.html"},
    {e:"📄", n:"YL-011 冰糖酸梅汤 · 沧林食品", d:"", f:"cards/YL_011.html"},
    {e:"📄", n:"手剥粒粒大橘 · 沧林食品", d:"", f:"cards/YL_012.html"},
    {e:"📄", n:"爆打黄皮香柠 · 沧林食品", d:"", f:"cards/YL_013.html"},
    {e:"📄", n:"香水爆柠油柑 · 沧林食品", d:"", f:"cards/YL_014.html"},
    {e:"📄", n:"真香桃桃爆柠 · 沧林食品", d:"", f:"cards/YL_015.html"},
    {e:"📄", n:"桑爆柠 · 沧林食品", d:"", f:"cards/YL_016.html"},
    {e:"📄", n:"悠悠青提山茶柠 · 沧林食品", d:"", f:"cards/YL_017.html"},
    {e:"📄", n:"青提油柑 · 沧林食品", d:"", f:"cards/YL_018.html"},
    {e:"📄", n:"满杯青提 · 沧林食品", d:"", f:"cards/YL_019.html"},
    {e:"📄", n:"超级多肉葡萄杨梅 · 沧林食品", d:"", f:"cards/YL_020.html"},
    {e:"📄", n:"葡萄撞撞百香冻 · 沧林食品", d:"", f:"cards/YL_021.html"},
    {e:"📄", n:"紫玉阳光青提 · 沧林食品", d:"", f:"cards/YL_022.html"},
    {e:"📄", n:"瓜桃儿墩墩 · 沧林食品", d:"", f:"cards/YL_023.html"},
    {e:"📄", n:"瓜桃儿优酪 · 沧林食品", d:"", f:"cards/YL_024.html"},
    {e:"📄", n:"桃桃蜜柚 · 沧林食品", d:"", f:"cards/YL_025.html"},
    {e:"📄", n:"桃桃小杏运 · 沧林食品", d:"", f:"cards/YL_026.html"},
    {e:"📄", n:"多肉桃李 · 沧林食品", d:"", f:"cards/YL_027.html"},
    {e:"📄", n:"芝芝云顶桃桃 · 沧林食品", d:"", f:"cards/YL_028.html"},
    {e:"📄", n:"紫苏桃桃饮 · 沧林食品", d:"", f:"cards/YL_029.html"},
    {e:"📄", n:"霸气杨梅 · 沧林食品", d:"", f:"cards/YL_030.html"},
    {e:"📄", n:"草莓撞撞百香冻 · 沧林食品", d:"", f:"cards/YL_031.html"},
    {e:"📄", n:"满杯鲜橙 · 沧林食品", d:"", f:"cards/YL_032.html"},
    {e:"📄", n:"好味油柑绿茶 · 沧林食品", d:"", f:"cards/YL_033.html"},
    {e:"📄", n:"霸气小确杏 · 沧林食品", d:"", f:"cards/YL_034.html"},
    {e:"📄", n:"喜柿多多 · 沧林食品", d:"", f:"cards/YL_035.html"},
    {e:"📄", n:"霸气山楂草莓 · 沧林食品", d:"", f:"cards/YL_036.html"},
    {e:"📄", n:"酷黑莓莓 · 沧林食品", d:"", f:"cards/YL_037.html"},
    {e:"📄", n:"太妃芝士奶咖 · 沧林食品", d:"", f:"cards/YL_038.html"},
    {e:"📄", n:"芭乐碰 · 沧林食品", d:"", f:"cards/YL_039.html"},
    {e:"📄", n:"鲜橙美式 · 沧林食品", d:"", f:"cards/YL_040.html"},
    {e:"📄", n:"椰青美式 · 沧林食品", d:"", f:"cards/YL_041.html"},
    {e:"📄", n:"生椰拿铁 · 沧林食品", d:"", f:"cards/YL_042.html"},
    {e:"📄", n:"抓马西瓜拿铁 · 沧林食品", d:"", f:"cards/YL_043.html"},
    {e:"📄", n:"绿豆牛乳冰 · 沧林食品", d:"", f:"cards/YL_044.html"},
    {e:"📄", n:"红豆牛乳冰 · 沧林食品", d:"", f:"cards/YL_045.html"},
    {e:"📄", n:"绿豆宝宝 · 沧林食品", d:"", f:"cards/YL_046.html"},
    {e:"📄", n:"土芭乐柠茶 · 沧林食品", d:"", f:"cards/YL_047.html"},
    {e:"📄", n:"满瓶芭乐葡 · 沧林食品", d:"", f:"cards/YL_048.html"},
    {e:"📄", n:"芭乐桃子酪酪 · 沧林食品", d:"", f:"cards/YL_049.html"},
    {e:"📄", n:"芭乐草莓酪酪 · 沧林食品", d:"", f:"cards/YL_050.html"},
    {e:"📄", n:"石榴酪酪 · 沧林食品", d:"", f:"cards/YL_051.html"},
    {e:"📄", n:"杨梅酪酪 · 沧林食品", d:"", f:"cards/YL_052.html"},
    {e:"📄", n:"霸气小确杏酪酪 · 沧林食品", d:"", f:"cards/YL_053.html"},
    {e:"📄", n:"玫瑰荔枝酪酪 · 沧林食品", d:"", f:"cards/YL_054.html"},
    {e:"📄", n:"多肉葡萄桑 · 沧林食品", d:"", f:"cards/YL_055.html"},
    {e:"📄", n:"经典蛋糕鲜奶茶 · 沧林食品", d:"", f:"cards/YL_056.html"},
    {e:"📄", n:"栗子麻薯鲜奶茶 · 沧林食品", d:"", f:"cards/YL_057.html"},
    {e:"📄", n:"黑糖鸭屎香鲜奶茶 · 沧林食品", d:"", f:"cards/YL_058.html"},
    {e:"📄", n:"山茶花鲜奶茶 · 沧林食品", d:"", f:"cards/YL_059.html"},
  ],
  "🥩 经典名鸡": [
    {e:"📄", n:"酱卤牛肉 · 完整产品卡 · 沧林食品工作站", d:"", f:"cards/酱卤牛肉_产品卡.html"},
    {e:"📄", n:"酱卤牛肉 · 完整工艺配方文档 · 沧林食品工作站", d:"", f:"cards/酱卤牛肉_工艺配方文档.html"},
  ],
  "🥩 韩式系列": [
    {e:"📄", n:"日式烧鸟·京葱鸡肉串 · 沧林食品", d:"", f:"cards/KR_001.html"},
    {e:"📄", n:"韩式烤五花肉 · 沧林食品", d:"", f:"cards/KR_002.html"},
    {e:"📄", n:"韩式烤牛舌 · 沧林食品", d:"", f:"cards/KR_003.html"},
    {e:"📄", n:"韩式调味牛排 · 沧林食品", d:"", f:"cards/KR_004.html"},
    {e:"📄", n:"韩式烤鱿鱼 · 沧林食品", d:"", f:"cards/KR_005.html"},
    {e:"📄", n:"韩式烤猪排 · 沧林食品", d:"", f:"cards/KR_006.html"},
  ],
  "🧂 复合酱料": [
    {e:"（", n:"葱香油（混合油） · 沧林食品", d:"", f:"cards/NF_001.html"},
    {e:"（", n:"江湖酱（复合辣酱） · 沧林食品", d:"", f:"cards/NF_002.html"},
    {e:"（", n:"万能拌面酱（基础酱） · 沧林食品", d:"", f:"cards/NF_003.html"},
    {e:"（", n:"辣子鸡丁（拌面浇头） · 沧林食品", d:"", f:"cards/NF_004.html"},
    {e:"（", n:"网红炒鸡（拌面浇头） · 沧林食品", d:"", f:"cards/NF_005.html"},
  ],
  "🧋 奶茶系列": [
    {e:"📄", n:"NT-01 港式丝袜奶茶 · 沧林食品", d:"", f:"cards/NT_01.html"},
    {e:"📄", n:"NT-02 鸭屎香奶茶 · 沧林食品", d:"", f:"cards/NT_02.html"},
    {e:"📄", n:"NT-03 泰绿奶茶 · 沧林食品", d:"", f:"cards/NT_03.html"},
    {e:"📄", n:"NT-04 糯香奶茶 · 沧林食品", d:"", f:"cards/NT_04.html"},
    {e:"📄", n:"NT-05 桃桃乌龙奶茶 · 沧林食品", d:"", f:"cards/NT_05.html"},
    {e:"📄", n:"NT-06 山茶花奶茶 · 沧林食品", d:"", f:"cards/NT_06.html"},
    {e:"📄", n:"NT-07 厚生耶拿铁 · 沧林食品", d:"", f:"cards/NT_07.html"},
    {e:"📄", n:"NT-08 富贵可可 · 沧林食品", d:"", f:"cards/NT_08.html"},
    {e:"📄", n:"NT-09 淮山红枣奶 · 沧林食品", d:"", f:"cards/NT_09.html"},
    {e:"📄", n:"NT-10 泰式街头咖啡 · 沧林食品", d:"", f:"cards/NT_10.html"},
    {e:"📄", n:"NT-11 好出奇冰柠茶 · 沧林食品", d:"", f:"cards/NT_11.html"},
    {e:"📄", n:"NT-12 招牌柠檬茶 · 沧林食品", d:"", f:"cards/NT_12.html"},
  ],
  "🫕 特色系列": [
    {e:"（", n:"柠檬鸡爪（无骨版） · 沧林食品", d:"", f:"cards/QS_001.html"},
    {e:"（", n:"捞汁小海鲜（花蛤基围虾版） · 沧林食品", d:"", f:"cards/QS_002.html"},
    {e:"📄", n:"韩式炸鸡 · QS-003 · 咔库秘制", d:"", f:"cards/QS_003.html"},
    {e:"📄", n:"酸嘢 · QS-004 · 咔库秘制", d:"", f:"cards/QS_004.html"},
    {e:"📄", n:"韩式炸鸡搭配品 · QS-005 · 咔库秘制", d:"", f:"cards/QS_005.html"},
    {e:"📄", n:"水泥麻辣烫 · QS-006 · 咔库秘制", d:"", f:"cards/QS_006.html"},
  ],
  "🫘 经典名鸡": [
    {e:"📄", n:"麻油鸡 · 酱卤工艺卡 · 沧林食品工作站", d:"", f:"cards/麻油鸡_产品卡.html"},
    {e:"📄", n:"洛阳麻油鸡 · 完整工艺配方文档 · 沧林食品工作站", d:"", f:"cards/麻油鸡_工艺配方文档.html"},
  ],
};


function renderAllCards() {
  const container = document.getElementById('hotContent');
  if (!container) return;
  
  container.innerHTML = '';
  const hotTags = ['🔥', '📈', '💥', '⭐', '💎', '🚀'];
  let tagIdx = 0;
  
  Object.keys(ALL_CARDS).forEach((catName, ci) => {
    const cards = ALL_CARDS[catName];
    const tagType = hotTags[tagIdx % hotTags.length];
    tagIdx++;
    
    // 分类标题
    container.innerHTML += '<div class="zone-hot-sub">' + catName + ' <span class="h-tag h-hot">' + tagType + '</span></div>';
    container.innerHTML += '<div class="zone-hot-cards">';
    
    cards.forEach((c, i) => {
      const rankClass = i===0 ? 'top1' : i===1 ? 'top2' : i===2 ? 'top3' : '';
      container.innerHTML += 
        '<a class="zone-hot-card" href="' + c.f + '">' +
          '<div class="rank ' + rankClass + '">' + (i+1) + '</div>' +
          '<div class="h-emoji">' + c.e + '</div>' +
          '<div class="h-info">' +
            '<div class="h-name">' + c.n + ' <span class="h-tag h-hot">' + tagType + '</span></div>' +
            '<div class="h-desc">' + c.d + '</div>' +
          '</div>' +
          '<div class="h-arrow">›</div>' +
        '</a>';
    });
    
    container.innerHTML += '</div>';
  });
}

// 替换原来的渲染
renderAllCards();
